name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - "main" # 推送到 main 分支时触发
    tags:
      - 'v*.*.*' # 推送形如 v1.0.0, v1.2.3 等标签时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # 重要：当 Action 由标签触发时，确保 checkout action 获取标签信息
        # 默认情况下，checkout action 会检出触发工作流的特定 SHA，
        # 如果是标签，它会检出与该标签关联的提交。
        # 对于 docker/metadata-action 来说，它能够正确识别标签事件。

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/chain-subconverter
          tags: |
            # 当事件是推送标签时 (例如 v1.2.3)，使用版本号作为标签
            type=semver,pattern={{version}}
            # 当推送到 main 分支时，或者任何其他非标签推送（如果配置了）时，打上 latest 标签
            # 为了确保 'latest' 总是指向 main 分支的最新构建 (如果这是期望行为)
            # 或者在标签推送时，也将该版本标记为 latest (如果需要)
            # 如果你希望 'latest' 只在推送到 main 分支时更新，
            # 并且标签推送时不更新 'latest'，你需要更复杂的条件。
            # 但通常，最新的发布版本也会被标记为 'latest'。
            type=raw,value=latest,enable={{is_default_branch}}
            # 如果你希望每个标签推送也更新 latest，可以去掉 enable={{is_default_branch}}
            # 或者更明确地：
            # type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # file: ./Dockerfile # 如果 Dockerfile 名称不是标准的 "Dockerfile"，则取消注释并指定
          push: true # 我们希望在 main 分支推送和标签推送时都进行推送
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max