name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - "dev"    # 当代码推送到 dev 分支时触发
    tags:
      - 'v*.*.*' # 当推送形如 v1.0.0, v1.2.3 等版本标签时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-push-dev:
    # 仅当推送到 dev 分支时运行此 job
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    name: Build and Push Dev Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 写入 GitHub Packages (ghcr.io) 的权限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Dev Docker Image
        id: meta_dev
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/chain-subconverter
          tags: |
            type=raw,value=dev  # 为最新的 dev 构建打上 'dev' 标签
            type=sha,prefix=dev-,format=short # 为每个 dev 构建打上 'dev-<short-sha>' 标签, 例如 dev-a1b2c3d

      - name: Build and push Dev Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true # 推送开发镜像
          tags: ${{ steps.meta_dev.outputs.tags }}
          labels: ${{ steps.meta_dev.outputs.labels }}
          platforms: linux/amd64,linux/arm64 # 根据需要调整平台
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-release:
    # 仅当推送版本标签 (v*.*.*) 时运行此 job
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    name: Build and Push Release Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # 写入 GitHub Packages (ghcr.io) 的权限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Release Docker Image
        id: meta_release
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/chain-subconverter
          tags: |
            type=semver,pattern={{version}} # 例如 Git 标签 v1.0.0 -> Docker 标签 1.0.0
            type=raw,value=latest          # 将最新的版本标签也标记为 latest

      - name: Build and push Release Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true # 推送发布镜像
          tags: ${{ steps.meta_release.outputs.tags }}
          labels: ${{ steps.meta_release.outputs.labels }}
          platforms: linux/amd64,linux/arm64 # 根据需要调整平台
          cache-from: type=gha
          cache-to: type=gha,mode=max
